name: KSOC Guard
description: KSOC finds misconfigurations in your Kubernetes posture as part of your GitHub Actions CI workflow.
author: KSOC
branding:
  icon: alert-triangle
  color: green

inputs:
  fail_on_severity:
    required: false
    description: "The severity level at which to fail the workflow. Valid values are: none, low, medium, high, critical."
    default: none
  format:
    required: false
    description: "The format of the output. Valid values are: ci-table, table."
    default: ci-table
  ignored_paths:
    required: false
    description: "Comma separated list of paths to ignore."
  ignored_policies:
    required: false
    description: "Comma separated list of policy IDs to ignore."
  ksoc_access_key_id:
    required: false
    description: "The KSOC access key ID."
  ksoc_account_id:
    required: false
    description: "The KSOC account ID."
  ksoc_api_url:
    required: false
    description: "The KSOC API URL."
    default: https://api.ksoc.com
  ksoc_secret_key:
    required: false
    description: "The KSOC secret key."
  paths:
    required: false
    description: "Comma separated list of paths to scan."
    default: "."
  policy_dir:
    required: false
    description: "The directory containing the policies to execute."
  policy_ids:
    required: false
    description: "Comma separated list of policy IDs to execute."
  policy_tags:
    required: false
    description: "Comma separated list of policy tags to execute."
outputs:
  results:
    description: "The results of the policy execution."
  sarif:
    description: "Path to a SARIF report file with the policy execution results."

runs:
  using: docker
  image: Dockerfile
  env:
    FAIL_ON_SEVERITY: ${{ inputs.fail_on_severity }}
    FORMAT: ${{ inputs.format }}
    IGNORED_PATHS: ${{ inputs.ignored_paths }}
    IGNORED_POLICIES: ${{ inputs.ignored_policies }}
    KSOC_ACCESS_KEY_ID: ${{ inputs.ksoc_access_key_id }}
    KSOC_ACCOUNT_ID: ${{ inputs.ksoc_account_id }}
    KSOC_API_URL: ${{ inputs.ksoc_api_url }}
    KSOC_SECRET_KEY: ${{ inputs.ksoc_secret_key }}
    PATHS: ${{ inputs.paths }}
    POLICY_DIR: ${{ inputs.policy_dir }}
    POLICY_IDS: ${{ inputs.policy_ids }}
    POLICY_TAGS: ${{ inputs.policy_tags }}
